//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWap.MyService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hbcom.vn/", ConfigurationName="MyService.ActionSoap")]
    public interface ActionSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Check(string Signature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Reg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Reg(int ChannelType, string Signature, string CommandCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/Dereg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Dereg(int ChannelType, string Signature, string CommandCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hbcom.vn/GetInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInfo(string Signature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActionSoapChannel : MyWap.MyService.ActionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActionSoapClient : System.ServiceModel.ClientBase<MyWap.MyService.ActionSoap>, MyWap.MyService.ActionSoap {
        
        public ActionSoapClient() {
        }
        
        public ActionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Check(string Signature) {
            return base.Channel.Check(Signature);
        }
        
        public string Reg(int ChannelType, string Signature, string CommandCode) {
            return base.Channel.Reg(ChannelType, Signature, CommandCode);
        }
        
        public string Dereg(int ChannelType, string Signature, string CommandCode) {
            return base.Channel.Dereg(ChannelType, Signature, CommandCode);
        }
        
        public System.Data.DataTable GetInfo(string Signature) {
            return base.Channel.GetInfo(Signature);
        }
    }
}
